### ISSUE TITLE
Hackerrank Algorithms - Mini-Max Sum (2016-12-28)

### ISSUE THREAD

**Issue by ubitoffee** [freshcheese/hackerrank#1]
[Mini-Max Sum 문제](https://www.hackerrank.com/challenges/mini-max-sum)

푸실 분들은 repository algorithms/mini-max-sum 폴더에 완료된 파일 업로드 해주세요

@daehwann 
@vincent-contreras

**Comment by ubitoffee** [comment]
문제 - 5개의 양의 정수중 4개를 합하여 나올수 있는 최소값과 최대값을 찾아라.

**Comment by ubitoffee** [comment]
f43d6e9d3ece993ca002f94547630a5a8040051e

**Comment by ubitoffee** [comment]
```java
int i = 0;
int j = 0;
```

**Comment by ubitoffee** [comment]
``` java
sum > Long.MAX_VALUE - longArr[j] //삭제
```

**Comment by vincent-contreras** [comment]
?? ??? ???! ???

For your information, this e-mail was sent via a mobile device named Voyager 2.
Please inform him if you got this message by mistake.

On 28 Dec 2016, at 11:29 AM, Jason Jeong <notifications@github.com<mailto:notifications@github.com>> wrote:


sum > Long.MAX_VALUE - longArr[j] //??

-

**Comment by ubitoffee** [comment]
@vincent-contreras 

What's that? Github mailing system broke Korean when it was in source comment :(

Or is all that comment mail's Korean broken???

**Comment by vincent-contreras** [comment]
핸드폰은 한국어 지원 못 하네 ㅎㅎㅎㅎ

한번 풀어 볼건다고 했어요.

문제 봤는데 어렵지 않군요 ㅎㅎㅎ
