### ISSUE TITLE
Hackerrank Algorithms - Shelock and Squares (2017-01-17)

### ISSUE THREAD

**Issue by ubitoffee** [freshcheese/hackerrank#17]
[Shelock and Squares 문제](https://www.hackerrank.com/challenges/sherlock-and-squares)

야근하느라 하루쉬었습니다 ㅎㅎ

**Comment by daehwann** [comment]
아니 일은 안해요?? ㅋㅋㅋ

**Comment by ubitoffee** [comment]
점심시간이었어요ㅋㅋ
짬날때마다 푸는거죠ㅎㅎ
